<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="landing" params="name parent *origin">

  <link name="origin_landing">
    <xacro:default_inertial/>
  </link>
  
  <joint name="joint_origin_landing" type="fixed">
    <insert_block name="origin" />
    <parent link="${parent}"/>
    <child link="origin_landing" />
  </joint> 

  <!-- wall ext -->
  <!--link name="wall_ext1">
    <xacro:box_inertial x="2.1" y="${wall_depth}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.1 ${wall_depth} ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.1 ${wall_depth} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext1">
    <material>IPA/WallApartment</material>
  </gazebo>

  <joint name="joint_wall_ext1" type="fixed">
    <origin xyz="8.8 2.565 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext1" />
  </joint--> 

  <!-- wall ext -->
  <link name="door_E334">
    <xacro:box_inertial x="2.2" y="${wall_depth}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.2 ${wall_depth} ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.2 ${wall_depth} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="door_E334">
    <material>door_E334</material>
  </gazebo>

  <joint name="joint_door_E334" type="fixed">
    <origin xyz="8.70 -1.565 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="door_E334" />
  </joint> 
  
  <!-- wall ext -->
  <link name="wall_ext3">
    <xacro:box_inertial x="${wall_depth}" y="1.73" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.73 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.73 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext3">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext3" type="fixed">
    <origin xyz="7.6 -1.7 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext3" />
  </joint> 

  <!-- wall ext -->
  <link name="wall_ext4">
    <xacro:box_inertial x="${wall_depth}" y="1.93" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.93 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.93 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext4">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext4" type="fixed">
    <origin xyz="7.58 1.83 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext4" />
  </joint> 

  <link name="wall_ext5">
    <xacro:box_inertial x="2.24" y="0.04" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.24 0.04 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.24 0.04 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext5">
    <material>door_opposite_of_men_toilet</material>
  </gazebo>

  <joint name="joint_wall_ext5" type="fixed">
    <origin xyz="6.55 -0.85 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext5" />
  </joint> 

  <link name="wall_ext6">
    <xacro:box_inertial x="2.24" y="0.04" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.24 0.04 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="2.24 0.04 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext6">
    <material>door_toilet_men</material>
  </gazebo>

  <joint name="joint_wall_ext6" type="fixed">
    <origin xyz="6.55 0.85 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext6" />
  </joint> 
  
  <!--office landing-->
  <!--link name="wall_ext7">
    <xacro:box_inertial x="${wall_depth}" y="2.1" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 2.1 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 2.1 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext7">
    <material>IPA/WallApartment</material>
  </gazebo>

  <joint name="joint_wall_ext7" type="fixed">
    <origin xyz="2.565 8.8 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext7" />
  </joint--> 

  <!-- wall ext -->
  <link name="wall_ext8">
    <xacro:box_inertial x="${wall_depth}" y="2.3" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 2.3 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 2.3 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext8">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_ext8" type="fixed">
    <origin xyz="-2.565 8.7 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext8" />
  </joint> 
  
  <!-- wall ext -->
  <link name="wall_ext9">
    <xacro:box_inertial x="1.73" y="${wall_depth}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.73 ${wall_depth} ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.73 ${wall_depth} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext9">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext9" type="fixed">
    <origin xyz="-1.8 7.50 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext9" />
  </joint> 

  <!-- wall ext -->
  <link name="wall_ext10">
    <xacro:box_inertial x="1.96" y="${wall_depth}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.96 ${wall_depth} ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.96 ${wall_depth} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext10">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext10" type="fixed">
    <origin xyz="1.89 7.53 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext10" />
  </joint> 

  <link name="wall_ext11">
    <xacro:box_inertial x="0.04" y="2.24" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 2.24 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 2.24 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext11">
    <material>door_women_toilet</material>
  </gazebo>

  <joint name="joint_wall_ext11" type="fixed">
    <origin xyz="-0.85 6.55 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext11" />
  </joint> 

  <link name="wall_ext12">
    <xacro:box_inertial x="0.04" y="2.24" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 2.24 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 2.24 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext12">
    <material>door_E322</material>
  </gazebo>

  <joint name="joint_wall_ext12" type="fixed">
    <origin xyz="0.85 6.55 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext12" />
  </joint> 

  <link name="wall_ext13">
    <xacro:box_inertial x="0.04" y="6.6" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 6.6 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 6.6 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext13">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext13" type="fixed">
    <origin xyz="3.15 3.15 ${size_z_wall1/2}" rpy="0 0 0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext13" />
  </joint>

  <link name="wall_ext14">
    <xacro:box_inertial x="${wall_depth}" y="6.6" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 6.6 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 6.6 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext14">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext14" type="fixed">
    <origin xyz="-3.15 3.15 ${size_z_wall1/2}" rpy="0 0 -0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext14" />
  </joint> 

  <link name="wall_ext15">
    <xacro:box_inertial x="0.04" y="6.6" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 6.6 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 6.6 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext15">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext15" type="fixed">
    <origin xyz="-3.15 -3.15 ${size_z_wall1/2}" rpy="0 0 0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext15" />
  </joint> 
  
  <link name="wall_ext16">
    <xacro:box_inertial x="0.04" y="1.8" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 1.8 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.04 1.8 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext16">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext16" type="fixed">
    <origin xyz="-5.4 0 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext16" />
  </joint> 
  
  <link name="wall_ext17">
    <xacro:box_inertial x="1.8" y="0.04" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.8 0.04 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.8 0.04 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext17">
    <material>wall_floor_07</material>
  </gazebo>

  <joint name="joint_wall_ext17" type="fixed">
    <origin xyz="0 -5.4 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext17" />
  </joint> 
  
  <link name="wall_ext21">
    <xacro:box_inertial x="${wall_depth}" y="6.75" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 6.75 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 6.75 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext21">
    <material>wall_livingroom2</material>
  </gazebo>

  <joint name="joint_wall_ext21" type="fixed">
    <origin xyz="5.20 5.15 ${size_z_wall1/2}" rpy="0 0 0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext21" />
  </joint> 
  
  <link name="wall_ext22">
    <xacro:box_inertial x="0.06" y="6.00" z="${size_z_wall2}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.06 6.00 ${size_z_wall2}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.06 6.00 ${size_z_wall2}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext22">
    <material>wall_livingroom1</material>
  </gazebo>

  <joint name="joint_wall_ext22" type="fixed">
    <origin xyz="7.65 7.79 ${size_z_wall2/2}" rpy="0 0 0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext22" />
  </joint> 
  
  <link name="wall_ext23">
    <xacro:box_inertial x="1.2" y="${wall_depth}" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.2 ${wall_depth} ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.2 ${wall_depth} ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext23">
    <material>wall_floor_06</material>
  </gazebo>

  <joint name="joint_wall_ext23" type="fixed">
    <origin xyz="9.22 2.83 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext23" />
  </joint> 

  <link name="wall_ext24">
    <xacro:box_inertial x="1.99" y="0.06" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.99 0.06 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="1.99 0.06 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext24">
    <material>livingroom_slidingdoor</material>
  </gazebo>

  <joint name="joint_wall_ext24" type="fixed">
    <origin xyz="9.058 4.958 ${size_z_wall1/2}" rpy="0 0 0.7854" />
    <parent link="origin_landing" />
    <child link="wall_ext24" />
  </joint> 

  <!-- wall ext25 -->
  <link name="wall_ext25">
    <xacro:box_inertial x="${wall_depth}" y="1.1" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.1 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 1.1 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext25">
    <material>wall_floor_06</material>
  </gazebo>

  <joint name="joint_wall_ext25" type="fixed">
    <origin xyz="2.81 9.3 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext25" />
  </joint> 

  <!-- wall ext26 -->
  <link name="wall_ext26">
    <xacro:box_inertial x="${wall_depth}" y="0.23" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 0.23 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} 0.23 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_ext26">
    <material>wall_floor_08</material>
  </gazebo>

  <joint name="joint_wall_ext26" type="fixed">
    <origin xyz="2.81 7.63 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="wall_ext26" />
  </joint> 

  <!-- pillar ext01 -->
  <link name="pillar_ext01">
    <xacro:box_inertial x="0.35" y="0.35" z="${size_z_wall1}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.35 0.35 ${size_z_wall1}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="0.35 0.35 ${size_z_wall1}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="pillar_ext01">
    <material>wall_floor_12</material>
  </gazebo>

  <joint name="joint_pillar_ext01" type="fixed">
    <origin xyz="1.08 9.675 ${size_z_wall1/2}" rpy="0 0 0" />
    <parent link="origin_landing" />
    <child link="pillar_ext01" />
  </joint>

  </xacro:macro>

</robot>
