<?xml version="1.0"?>
<robot name="cabinet"
	xmlns:xacro="http://www.ros.org/wiki/xacro"
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
	xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
	xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
	xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
	xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
>

  <xacro:property name="cabinet_height" value="1.06" />
  <xacro:property name="cabinet_width" value="0.28" />
  <xacro:property name="cabinet_depth" value="0.40" />
  <xacro:property name="cabinet_x" value="1.5" />
  <xacro:property name="cabinet_y" value="0.0" />
  <xacro:property name="cabinet_z" value="0.0" />


<!-- dummy_link -->
	<link name="dummy_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.00 0.00 0.00" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.00 0.00 0.00" />
			</geometry>
		</collision>
	</link>


<!-- cabinet -->

	<!-- cabinet_structure -->
	<link name="cabinet_structure">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${cabinet_width} ${cabinet_depth} ${cabinet_height}" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${cabinet_width} ${cabinet_depth} ${cabinet_height}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="cabinet_structure">
		<material>Gazebo/White</material>
	</gazebo>

	<joint name="joint_structure" type="fixed">
		<origin xyz="0.000 0.000 ${cabinet_height/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="cabinet_structure" />
	</joint>



	<!-- cabinet_door -->
	<link name="cabinet_door">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="1.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 ${cabinet_depth} ${cabinet_height-0.08}" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 ${cabinet_depth} ${cabinet_height-0.08}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="cabinet_door">
		<material>Gazebo/White</material>
	</gazebo>

	<joint name="joint_door" type="fixed">
		<origin xyz="${-cabinet_width/2} 0.000 0.04" rpy="0 0 0" />
		<parent link="cabinet_structure" />
		<child link="cabinet_door" />
	</joint>

	<!--knob1-->
	<link name="knob1_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="1.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.015 0.01" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.015 0.01" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="knob1_link">
		<material>Gazebo/Grey</material>
	</gazebo>

	<joint name="joint_knob1" type="fixed">
		<origin xyz="${-0.015} ${-cabinet_depth/2+0.0175} ${(cabinet_height-0.08)/2-0.06}" rpy="0 0 0" />
		<parent link="cabinet_door" />
		<child link="knob1_link" />
	</joint>

	<!--knob2-->
	<link name="knob2_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="1.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.015 0.01" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.015 0.01" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="knob2_link">
		<material>Gazebo/Grey</material>
	</gazebo>

	<joint name="joint_knob2" type="fixed">
		<origin xyz="${-0.015} ${-cabinet_depth/2+0.0175} ${(cabinet_height-0.08)/2-0.06-0.13}" rpy="0 0 0" />
		<parent link="cabinet_door" />
		<child link="knob2_link" />
	</joint>

	<!--knob3-->
	<link name="knob3_link">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="1.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.01 0.015 0.14" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.01 0.015 0.14" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="knob3_link">
		<material>Gazebo/Grey</material>
	</gazebo>

	<joint name="joint_knob3" type="fixed">
		<origin xyz="-0.02 0 -0.065" rpy="0 0 0" />
		<parent link="knob1_link" />
		<child link="knob3_link" />
	</joint>
</robot>
