<?xml version="1.0"?>
<robot name="chair"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

  <property name="chair_height" value="0.45" />
  <property name="chair_width" value="0.4" />
  <property name="chair_depth" value="0.4" />
  <property name="chair_y" value="0.0" />
  <property name="chair_z" value="0.0" />
  <property name="rest_height" value="0.5" />

  <property name="chair_top_thickness" value="0.02"/>

  <property name="M_PI" value="3.1415926535897931" />


  <link name="chair_top_link">
    <inertial>
      <mass value="5.0" />
      <origin xyz="0.0 0.0 0.0" />
      <inertia ixx="0" ixy="0"  ixz="0"
               iyy="0" iyz="0"
               izz="0" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${chair_z+chair_height-chair_top_thickness/2}" />
      <geometry>
        <box size="${chair_width} ${chair_depth} ${chair_top_thickness}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${chair_z+chair_height-chair_top_thickness/2}" />
      <geometry>
        <box size="${chair_width} ${chair_depth} ${chair_top_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="chair_top_link">
    <material>Gazebo/White</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>

  <link name="chair_rest_link">
    <inertial>
      <mass value="5.0" />
      <origin xyz="0.0 0.0 0.0" />
      <inertia ixx="0" ixy="0"  ixz="0"
               iyy="0" iyz="0"
               izz="0" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${chair_width} ${chair_top_thickness} ${rest_height}" />
      </geometry>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
        <box size="${chair_width} ${chair_top_thickness} ${rest_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="chair_rest_link">
    <material>Gazebo/White</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
  </gazebo>
      <joint name="chair_rest_joint" type="fixed" >
    	<parent link="chair_top_link" />
    	<origin xyz="0.0 ${chair_depth/2} ${chair_z+chair_height+rest_height/2}" rpy="0 0 0" />
        <child link="chair_rest_link" />
      </joint> 

    <macro name="legs" params="suffix parent pos1 pos2">

        
        <link name="leg_${suffix}_link">
            <inertial>
		<origin xyz="0 0 0" />
                <mass value="3" />
                <inertia  ixx="0" ixy="0" ixz="0"
                          iyy="0" iyz="0"
                          izz="0" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" />
                <geometry>
                    <box size="0.055 0.055 ${chair_height-chair_top_thickness}" />
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" />
                <geometry>
                    <box size="0.055 0.055 ${chair_height-chair_top_thickness}" />
                </geometry>
            </collision>
        </link>
	 
	<gazebo reference="legs">
		<material>Gazebo/White</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
      <joint name="leg_${suffix}_joint" type="fixed" >
    	<parent link="chair_top_link" />
    	<origin xyz="${0.0+pos1*(chair_width/2-0.0375)} ${chair_y+pos2*(chair_depth/2-0.0375)} ${chair_z+chair_height/2}" rpy="0 0 0" />
        <child link="leg_${suffix}_link" />
      </joint> 


  </macro>
        <legs suffix="left_front" parent="chair_top_link"  pos1="1" pos2="1"/>
	<legs suffix="left_back" parent="chair_top_link"  pos1="-1" pos2="1"/>
        <legs suffix="right_front" parent="chair_top_link"  pos1="1" pos2="-1"/>
	<legs suffix="right_back" parent="chair_top_link"  pos1="-1" pos2="-1"/>

 <!--macro name="structure_lath" params="suffix parent pos1 pos2 box_size">

        
        <link name="lath_${suffix}_link">
            <inertial>
		<origin xyz="0 0 0" />
                <mass value="1" />
                <inertia  ixx="0" ixy="0" ixz="0"
                          iyy="0" iyz="0"
                          izz="0" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" />
                <geometry>
		    <box size="${box_size}" />
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" />
                <geometry>
		    <box size="${box_size}" />
                </geometry>
            </collision>
        </link>
	 
	<gazebo reference="structure_lath">
		<material>Gazebo/White</material>
		<turnGravityOff>false</turnGravityOff>
	</gazebo>
      <joint name="lath_${suffix}_joint" type="fixed" >
    	<parent link="chair_top_link" />

    	<origin xyz="${0.0+pos1*(chair_width/2-0.02)} ${chair_y+pos2*(chair_depth/2-0.02)} ${chair_z+chair_height-chair_top_thickness-0.035}" rpy="0 0 0" />
        <child link="lath_${suffix}_link" />
      </joint> 

  </macro>

        <structure_lath suffix="left_front" parent="chair_top_link"  pos1="1" pos2="0" box_size="0.02 0.77 0.07"/>
	<structure_lath suffix="left_back" parent="chair_top_link"  pos1="-1" pos2="0" box_size="0.02 0.77 0.07"/>
        <structure_lath suffix="right_front" parent="chair_top_link"  pos1="0" pos2="1" box_size="0.77 0.02 0.07"/>
	<structure_lath suffix="right_back" parent="chair_top_link"  pos1="0" pos2="-1" box_size="0.77 0.02 0.07"/--> 

</robot>
